firstnumber = int(input("First Number: "))
secondnumber = int(input("Second Number: "))
thirdnumber = int(input("Third Number: "))
sum = int(firstnumber) + int(secondnumber) + int(thirdnumber)
print(sum)